### ISSUE TITLE
Jenkins 을 통한 NPM Publish 자동화

### ISSUE THREAD

**Issue by wileyday** [coolsms/coolsms-sdk-js-v4#7]

**Comment by wileyday** [comment]
Jenkins 오류
---------------

test
       
       config
         ✓ API_KEY, API_SECRET 검사
         ✓ ACCESS_TOKEN 검사
         ✓ default 검사
       
       group
         ✓ 그룹 생성 (그룹 아이디 확인)
         ✓ 그룹 메시지 추가 (none message)
         ✓ 그룹 메시지 추가 (none autoDetectType and type)
         ✓ 그룹 메시지 추가 (그룹 생성 전)
         ✓ 그룹 메시지 추가 (배열로)
         ✓ 그룹 메시지 추가 (오브젝트로)
         1) 그룹 메시지 발송 (성공)
         ✓ 그룹 삭제 (정상)
         2) 그룹 삭제 (PENDING 이 아닌경우)
         ✓ 그릅 정보 조회 (정상)
         ✓ 그릅 정보 조회 (생성 전)
         ✓ 그릅 목록 조회 (성공)
         ✓ 그릅 예약 (성공)
         ✓ 그릅 예약 (실패)
       
       message
         ✓ 메시지 리스트 조회 (그룹 생성 전)
         ✓ 메시지 리스트 조회 (정상)
         3) 심플 메시지 (정상)

   Executed 20 tests in 4 suites in 1s 504ms
       17 passes
       3 failed
   
   3) test message 심플 메시지 (정상)
   
       the object {
         "errorCode": "InvalidAccountId"
         "errorMessage": "Account ID가 유효하지 않습니다."
       } was thrown, throw an Error :)
       
       at Runner.fail (node_modules/mocha-clean/index.js:37:14)
       
       36 |   err = __mocha_internal__cleanError(err);
       37 |   return old.call(this, test, err);
       38 | };
       
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:182:7)
   
   2) test group 그룹 삭제 (PENDING 이 아닌경우)
   
       expected undefined to equal 'NotOperationalStatus'
       
       at Context.it (tests/test.js:123:33)
       
       122 |       }
       123 |       expect(data.errorCode).to.equal('NotOperationalStatus')
       124 |       expect(data.errorMessage).to.equal('PENDING 상태의 그룹만 삭제할 수 있습니다. 현재 상태는 SENDING 입니다.')
       
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:182:7)
   
   1) test group 그룹 메시지 발송 (성공)
   
       the object {
         "errorCode": "InvalidAccountId"
         "errorMessage": "Account ID가 유효하지 않습니다."
       } was thrown, throw an Error :)
       
       at Runner.fail (node_modules/mocha-clean/index.js:37:14)
       
       36 |   err = __mocha_internal__cleanError(err);
       37 |   return old.call(this, test, err);
       38 | };
       
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:182:7)
npm ERR! Test failed.  See above for more details.
Build step 'Execute shell' marked build as failure
Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
Finished: FAILURE
